---
title: "Massachusetts Census Analysis"
format: html
---

# Introduction


# Libraries


```{r}

library(tidycensus)
library(dplyr)
library(ggplot2)
library(scales)
library(plotly)
library(tidyr)
library(hexbin)
library(RColorBrewer)
library(forcats)
library(crosstalk)
library(mapview)
library(patchwork)
library(ggiraph)
library(mapdeck)
library(survey)

library(srvyr)

library(sf)

library(jsonlite)

library(tigris)

library(stringr)

library(leaflet)
library(htmlwidgets)
library(htmltools)
library(gt)
library(DT)
library(quarto)
library(purrr)


```





# Importing Census Data


```{r}






```


```{r}
#| echo: false


Sys.getenv("CENSUS_API_KEY")

```


```{r}


pop_2020<-load_variables(2020,"pl",cache=TRUE)



```

```{r}

dec_variable1_2020<-load_variables(2020, "sf1")



```


# State 

```{r}

mass <- get_estimates(
  geography = "state",
  state = "MA",
  product = "characteristics",
  breakdown = c("SEX", "AGEGROUP"),
  breakdown_labels = TRUE,
  vintage = 2024
)



```


```{r}


saveRDS(mass, "mass.rds")


```


```{r}



mass_filtered <- filter(mass, str_detect(AGEGROUP, "^Age"),
SEX != "Both sexes") |> 
  mutate(value = ifelse(SEX == "Male", -value, value))




```


```{r}


saveRDS(mass_filtered, "mass_filtered.rds")


```

```{r}

mass_filtered




```


```{r}

mass_ageSex_payramid <- ggplot(mass_filtered,
                               aes(x = AGEGROUP,
                               y = value,
                               fill = SEX)) +
  geom_bar(stat = "identity", width = 1) +
  theme_minimal(base_family = "Verdana") +
  scale_y_continuous(
    labels = function(y) paste0(abs(y/ 1000),"k")) +
    scale_x_discrete(labels = function(x) gsub("Age | years", "", x)) +
    scale_fill_manual(values = c("darkred", "navy")) +
    coord_flip() +
    labs(x = "",
         y = "2024 Census Bureau population estimate",
         title = "Population structure in Massachusetts",
         fill = "",
         )




```


```{r}


ggplotly(mass_ageSex_payramid)



```

# County


```{r}


ma_county_pop <- get_decennial(
  geography = "county",
  state = "MA",
  variables = "P1_001N",
  year=2020
) |> 
 mutate(NAME = str_remove(NAME, "County, Massachusetts"))


```


```{r}

ma_county_pop



```


```{r}


saveRDS(ma_county_pop, "ma_county_pop.rds")


```



```{r}


ma_county_pop <- readRDS("ma_county_pop.rds")


```

```{r}

ma_county_pop_plot<-ggplot(ma_county_pop, aes(x = value, y = reorder(NAME, value))) +
  geom_col(color = "darkgreen")+
  labs(title = "Massachusetts population by county",
        subtitle = "2020 Decential Census",
        x="Population",
        y = "") 




```

```{r}

saveRDS(ma_county_pop_plot, "ma_county_pop_plot.rds")


```

```{r}


ma_county_pop_plot <- readRDS("ma_county_pop_plot.rds")



```

```{r}



ma_county_pop_plot



```

```{r}

ggplotly(ma_county_pop_plot)


```


```{r}


vlac5<-load_variables(2020,"acs5",cache=TRUE)


```


```{r}


ac5_2125<-load_variables(2021,"acs5",cache=TRUE)



```

```{r}

ac5_1923 <- load_variables(2019,"acs5",cache=TRUE)



```

```{r}
ac5_1923



```



```{r}


ma_county_median_age <- get_acs(
    geography = "county",
    state = "MA",
    variables = "B01002_001",
    year=2019
)


```


```{r}



saveRDS(ma_county_median_age,"ma_county_median_age.rds")


```


```{r}

ma_county_median_age <- readRDS("ma_county_median_age.rds")



```

```{r}


ma_county_median_age



```


```{r}

load_variables(2019, "acs1/profile")


```


```{r}





```


```{r}

ma_college<-get_acs(
  geography = "county",
  variables = "DP02_0068P",
  state="MA",
  year=2019
)



```

```{r}

ma_college



```


```{r}


saveRDS(ma_college, "ma_college.rds")



```

```{r}

ma_college <- readRDS("ma_college.rds")



```


```{r}

college_vars <- c("B15002_015",  "B15002_016",  "B15002_017",  "B15002_018",  "B15002_032",  "B15002_033", "B15002_034",  "B15002_035") 







```


```{r}

years <- 2010:2019
names(years) <- years
college_by_year <- map_dfr(years, ~{
  get_acs(
    geography = "county",
    variables = college_vars,
    state="MA",
    summary_var = "B15002_001",
    survey="acs1",
    year = .x

  )
}, .id="year")



```


```{r}

saveRDS(college_by_year, "college_by_year.rds")


```

```{r}


college_by_year <- readRDS("college_by_year.rds")


```

```{r}


college_by_year |> 
  arrange(NAME, variable,year)


```

```{r}


percent_college_by_year <- college_by_year |> 
  group_by(NAME, year) |> 
  summarise(numerator = sum(estimate),
  denominator = first(summary_est)) |> 
  mutate(pct_college = 100 * (numerator / denominator)) |> 
  pivot_wider(id_cols = NAME,
              names_from = year,
              values_from = pct_college)


```



```{r}

saveRDS(percent_college_by_year, "percent_college_by_year.rds")



```


```{r}


percent_college_by_year <- readRDS("percent_college_by_year.rds")

```

```{r}

percent_college_by_year



```





```{r}

ma_county_incAge_wide<-get_acs(
  geography = "county",
  state="Massachusetts",
  variables = c(medinc="B19013_001",
                medage="b01002_001" ),
  output = "wide",
  year=2023
)



```


```{r}


saveRDS(ma_county_incAge_wide, "ma_county_incAge_wide.rds")


```







```{r}


ma_county_income <- get_acs(
  state = "Massachusetts",
  geography = "county",
  variables = c(hhincome = "B19013_001"),
  year = 2023,
) |> 
  mutate(NAME = str_remove(NAME, " County, Massachusetts"))





```


```{r}


saveRDS(ma_county_income, "ma_county_income.rds")


```


```{r}

ggplot(ma_county_income, aes(x = estimate, y = reorder(NAME, estimate))) +
  geom_point(size = 3, color = "darkgreen") +
  labs(title = "Median household income",
        subtitle = "Counties in Massachusetts",
        x="",
        y = "ACS estimate") +
  theme_minimal(base_size = 12.5)+
  scale_x_continuous(labels = label_dollar())



```

```{r}


ma_county_income |> 
  arrange(desc(moe))

```

```{r}

ggplot(ma_county_income, aes(x = estimate, y = reorder(NAME, estimate))) +
  geom_errorbarh(aes(xmin = estimate - moe, xmax = estimate + moe)) +
  geom_point(size = 3, color = "darkgreen") +
  labs(title = "Median household income",
        subtitle = "Counties in Massachusetts",
        x = "2019-2023 ACS estimnate",
        y = "") +
  theme_minimal(base_size = 12.5)+
  scale_x_continuous(labels = label_dollar())




```


```{r}


ma_income <- get_acs(
  geography = "county",
  variables = "B19013_001",
  state = "MA",
  year = 2023,
  geometry = TRUE
) |> 
  mutate(NAME = str_remove(NAME, "County, Massachusetts"))


```

```{r}

saveRDS(ma_income, "ma_income.rds")


```

```{r}


ma_income <- readRDS("ma_income.rds")


```






```{r}


ma_map <- ggplot(ma_income, aes(fill = estimate)) +
  geom_sf_interactive(aes(data_id = GEOID)) +
  scale_fill_distiller(palette = "Greens",
                       direction = 1,
                       guide = 'none') +
  theme_void()




```


```{r}

saveRDS(ma_map, "ma_map.rds")



```


```{r}


ma_mp <- readRDS("ma_map.rds")


```


```{r}



ma_plot <- ggplot(ma_income, aes(x = estimate, y = reorder(NAME, estimate),fill = estimate)) +
  geom_errorbar(aes(xmin = estimate -moe, xmax = estimate + moe)) +
  geom_point_interactive(color = "black", size = 4, shape = 21, aes(data_id = GEOID)) +
  scale_fill_distiller(palette = "Greens", direction = 1, labels = label_dollar()) +
  scale_x_continuous(labels = label_dollar()) +
  labs(title = "Household income by county in Massachusetts",
       subtitle = "2019-2023 American Community Survey",
       y = "",
       x = "ACS estimate (bars represent margin of error)",
       fill = "ACS estimate") +
  theme_minimal(base_size = 14)



```

```{r}


saveRDS(ma_plot, "ma_plot.rds")


```


```{r}


ma_plot <- readRDS("ma_plot.rds")


```


```{r}

girafe(ggobj = ma_map + ma_plot, width_svg = 10, height_svg = 5) |> 
  girafe_options(opts_hover(css = "fill:cyan;"))




```



The wide error bars for Nantucket and Duke counties are probably duie to their small populations.  Reference the county population plot for a comparison. 



```{r}



ma_county_home_value <- get_acs(
  geography = "county",
  variables = "B25077_001",
  state = "MA",
  survey = "acs1",
  year = 2023,
  geometry = TRUE
)



```


```{r}


saveRDS(ma_county_home_value, "ma_county_home_value.rds")


```





```{r}

ma_home_map <- ggplot(ma_county_home_value, aes(fill = estimate)) +
  geom_sf_interactive(aes(data_id = GEOID)) +
  scale_fill_distiller(palette = "Blues",
                       direction = 1,
                       guide = 'none') +
  theme_void()



```


```{r}

saveRDS(ma_home_map, "ma_home_map.rds")



```


```{r}


ma_home_plot <- ggplot(ma_county_home_value, aes(x = estimate, y = reorder(NAME, estimate),fill = estimate)) +
  geom_errorbar(aes(xmin = estimate -moe, xmax = estimate + moe)) +
  geom_point_interactive(color = "black", size = 4, shape = 21, aes(data_id = GEOID)) +
  scale_fill_distiller(palette = "Blues", direction = 1, labels = label_dollar()) +
  scale_x_continuous(labels = label_dollar()) +
  labs(title = "Median home value by county in Massachusetts",
       subtitle = "2019-2023 American Community Survey",
       y = "",
       x = "ACS estimate (bars represent margin of error)",
       fill = "ACS estimate") +
  theme_minimal(base_size = 14)




```


```{r}

saveRDS(ma_home_plot, "ma_home_plot.rds")



```


```{r}


girafe(ggobj = ma_home_map + ma_home_plot, width_svg = 10, height_svg = 5) |> 
  girafe_options(opts_hover(css = "fill:cyan;"))


```


```{r}


ma_county_home_value


```

```{r}


suffolk_flows <- get_flows(
  geography = "county",
  state = "MA",
  county = "Suffolk",
  geometry = TRUE
)



```

```{r}

saveRDS(suffolk_flows, "suffolk_flows.rds")



```

```{r}


suffolk_outflow <- get_flows(
  geography = "county",
  state = "MA",
  county = "Suffolk",
  geometry = TRUE
) |> 
filter(variable == "MOVEDOUT")  |> 
na.omit() |> 
arrange(desc(estimate))



```


```{r}

suffolk_inflow <- get_flows(
  geography = "county",
  state = "MA",
  county = "Suffolk",
  geometry = TRUE
) |> 
  na.omit() |> 
  arrange(desc(estimate))




```


```{r}


suffolk_outflow


```



```{r}


set_token(token)

```

```{r}



suffolk_outflow |> 
  slice_max(estimate, n= 30) |> 
  mutate(weight = estimate / 500) |> 
  mapdeck(token = token) |> 
  add_arc(origin = "centroid1",
          destination = "centroid2",
          stroke_width = "weight",
          update_view = FALSE)




```


```{r}

suffolk_inflow |> 
  slice_max(estimate, n= 30) |> 
  mutate(weight = estimate / 500) |> 
  mapdeck(token = token) |> 
  add_arc(origin = "centroid2",
          destination = "centroid1",
          stroke_width = "weight",
          update_view = FALSE)



```

# Tract

```{r}



suffolk_bachelors <- get_acs(
  geography = "tract",
  variables = "DP02_0068P",
  year = 2023,
  state = "MA",
  county = "Suffolk",
  geometry = TRUE
)


```


```{r}


saveRDS(suffolk_bachelors, "suffolk_bachelors.rds")


```

```{r}


mapview(suffolk_bachelors, zcol="estimate")


```



```{r}




middlesex_bachelors <- get_acs(
  geography = "tract",
  variables = "DP02_0068P",
  year = 2023,
  state = "MA",
  county = "Middlesex",
  geometry = TRUE
)


```


```{r}


saveRDS(middlesex_bachelors, "middlesex_bachelors.rds")


```


```{r}


mapview(middlesex_bachelors, zcol="estimate")

```


```{r}



norfolk_bachelors <- get_acs(
  geography = "tract",
  variables = "DP02_0068P",
  year = 2023,
  state = "MA",
  county = "Norfolk",
  geometry = TRUE
)


```

```{r}


saveRDS(norfolk_bachelors, "norfolk_bachelors.rds")


```

```{r}


mapview(norfolk_bachelors, zcol="estimate")


```


```{r}


dukes_bachelors <- get_acs(
  geography = "tract",
  variables = "DP02_0068P",
  year = 2023,
  state = "MA",
  county = "Dukes",
  geometry = TRUE
)



```


```{r}



saveRDS(dukes_bachelors, "dukes_bachelors.rds")


```




```{r}



mapview(dukes_bachelors, zcol="estimate")


```





```{r}

worcester_bachelors <- get_acs(
  geography = "tract",
  variables = "DP02_0068P",
  year = 2023,
  state = "MA",
  county = "Worcester",
  geometry = TRUE
)



```



```{r}



saveRDS(worcester_bachelors, "worcester_bachelors.rds")


```



```{r}


mapview(worcester_bachelors, zcol="estimate")



```




```{r}



hampshire_bachelors <- get_acs(
  geography = "tract",
  variables = "DP02_0068P",
  year = 2023,
  state = "MA",
  county = "Hampshire",
  geometry = TRUE
)


```



```{r}



saveRDS(hampshire_bachelors, "hampshire_bachelors.rds")


```



```{r}



mapview(hampshire_bachelors, zcol="estimate")


```



```{r}




```